### ISSUE TITLE
提供Serverless部署教程吗

### ISSUE THREAD

**Issue by cxw620** [ATQQ/node-server#16]
如题.

**Comment by ATQQ** [comment]
你是想部署到哪个云商的服务上呢

**Comment by ATQQ** [comment]
这里有一篇之前🐴的文，你可以先参考一下 [Serverless实践-Node服务上线部署](https://juejin.cn/post/6974416943600107533)

**Comment by ATQQ** [comment]
这个仓库只是 [flash-wolves](https://github.com/ATQQ/flash-wolves) 库的一个demo 模板 😋

**Comment by cxw620** [comment]
非常感谢!
